pdf(file="heatmap.pdf")
x <- read.table("samples_correlations_with_metadata.tsv", col.names=c("sample1","sample2","correl"), sep="\t")
#y <- reshape(x, direction="wide", v.names="sample1", timevar="sample2", idvar="correl")
#y <- reshape(x, direction="wide", v.names="sample1", timevar="sample2", idvar="correl")
library(reshape)
y <- cast(x, sample1 ~ sample2)
library(gplots)
y2=as.matrix(y)
#y2 = y2[rowSums(!is.na(x))!=0, colSums(!is.na(x))!=0] 
library(RColorBrewer)
heatmap.2(y2, trace="none",mar=c(1,15),col=brewer.pal(9,"YlOrRd"),cexCol=0.9, cexRow=0.1, dendrogram="row",labCol=FALSE)
dev.off()
